== Introduction

This model considers addresses - 'street addresses' - to be a form of compound name for a geospatial feature. For example, the Australian address:

----
72 Yundah Street
Shorncliffe QLD
4017 Australia
----

is a form of name for the cadastral parcel that defines a particular property's extend - a 'lot'.

Addresses modelled according to this model do more than just name things though: they are linked to geocodes - spatial points - allowing for map-based locating and route planning, sometimes other addresses for the same spatial object, sometimes parent/child addresses for dwelling compounds and management information such as lifecycle stages.

Overall, this model represents addresses, certain properties for them, including address parts, geocodes and the objects to which addresses are assigned in a conceptual manner similar to the international addressing standard, <<ISO19160-1>>. However, this model is expressed in Semantic Webfootnote:[See https://en.wikipedia.org/wiki/Semantic_Web for a general description of the Semantic Web] form, rather than ISO19160-1's UML and XML, and many aspects of the conceptual range that ISO19160 covers this model does not directly cover but instead delegates to other models which it imports, such as the representation of address and address part lifecycle information. This is done so that common things that this model does are available for use elsewhere via a series of mini-models that others may use without importing this whole model.

Additionally, this model relies on several specialised sub-models to handle specific types of address parts, such as roads and geographical object naming. By doing this, those things many be modelled independently of addressing and roads and geographic object names datasets can be used with address data very easily.

This model makes no attempt to model the things to which addresses are assigned. In the example above, the address "72 Yundah St...." is mentioned as being a form of name for, or assigned to, a cadastral parcel or a 'lot'. This model doesn't know what those things are and leaves their modelling to other systems. This means that using this model alone, you cannot know what an address is for unless you implement an address part to describe the type of object the address is assigned to. This decision has been made since there could be great complexity in spatial object / infrastructure modelling that isn't really core to addressing, so that's best left to other, likely sophisticated, models.


=== Sources of Requirements

In 2021, the Australia and New Zealand https://www.icsm.gov.au/[Intergovernmental Committee on Surveying and Mapping] established an https://www.icsm.gov.au/publications/addressing-2035[Addressing 2035 Strategy] that aimed to "provide leadership, coordination and standards for assembling, delivering and maintaining address datasets". The Strategy listed "Strategic Pillars", such as "Jurisdictional flexibility" - things for Strategy implementers to aim for - "Guiding Principles", "Overarching Pain Points" and other system/model/situation requirements. While the Strategy did not present an address model, it had an addendum that listed 10 requirements for a future address data model: https://www.icsm.gov.au/publications/addressing-strategy-information-addendum[Addendum to the Strategy]. These 10 requirements are a major source of this Address Models requirements.

These ICSM requirements include both specific requirements, for example to cater for "Multi-lingual and alternate name addressing", and also requirements to align with other address-related initiative which might be a source of multiple individual requirements, for example "Model interoperability" which, in its detailed description, indicates a requirement for an address model to align with a baseline set of spatial data standards that ICSM might create.

<<AnnexA>> lists the ICSM Addressing 2035 Strategy Addendum's 10 requirements and indicates how this model implements solutions for them.


=== Major Modelling Principles

Major modelling principles present in this model are:

. <<Model Reuse>>
. <<External Vocabularies>>
. <<Feature / Feature Naming differentiation>>
. <<Feature / Geometry differentiation>>
. <<Geocodes>>
. <<Address Parts>>
. <<Road & Geographical Names>>
. <<Address part typing>>
. <<Address part templating>>
. <<Water Addressing>>
. <<Related Addresses>>
. <<Lifecycles>>
. <<Profile Views>>

These principles are explained in the following subsections and the first two reference the following figure.


==== Model Reuse

The Semantic Web contains many widely-used models and model reuse is a greatly favoured practice for Semantic Web modelling for, if models are reused, data created according to them is instantly compatible with other data. Additionally, many Semantic Web models have deep thought behind them that no single modelling initiative could hope to match easily.

The well-known Semantic Web models that this model inherits from are:

* Web Ontology Language <<OWL>>: a widely-used set theory-based general-purpose model that uses the <<RDF>> data structure
* schema.org <<SDO>>: a general-purpose model of classes and properties used by many website publishers to present structured data to search engines
* GeoSPARQL <<GEO>>: the Open Geospatial Consortium'sfootnote:[The OGC: https://www.ogc.org/] ontology for basic features and geometries modelling
* Simple Knowledge Organization System <<SKOS>>: a simple OWL model for organizing taxonomies of concepts

Some aspects of addressing that were originally modelled within this model at its first release in 2021 have been discovered to be generic in nature but yet not already modelled in a Semantic Web ontology appropriate for use here. For those aspects of addressing, a series of mini-models have been created to allow the generic parts to be published independently of addressing, allowing for independent and hopefully greater reuse. The main mini-models factored out of this model are:

* Compound Naming Model <<CNM>>: modelling of names objects, parts of names, and the things names are assigned to
* Lifecycles Model <<LM>>: modelling of lifecycles for anything - whole addresses, parts of addresses etc.


==== External Vocabularies

Some elements of addresses must be subclassified by, or in some other way associated with, terms from vocabularies. The most prominent example is the expression of the type of part of an address: is it a _street number_, a _flat type_ or a _postcode_?

Where such vocabularies are used, they are not directly published _within_ this model but externally and this model is expected to be used with them. In this way, vocabularies may be extended without extending this model and different users may implement their own vocabularies to suite their business needs, for example, perhaps not all model users allow all address part types Queensland does, such as _water feature number_ so, they should use this model with a vocabulary that excludes that term.

See the <<Supporting Vocabularies>> section for mode information.


==== Feature / Feature Naming differentiation

This model details the elements of an _address_ but not details of the spatial objects that addresses are assigned to. The general conceptual split of address/spatial object follows the Address/AddressableObject split in ISO19160-1 <<ISO19160-1>>. Addresses are seen as a form of complex, multi-part, name for a spatial Feature.

This allows for the representation, and ultimately the management, of names - text, numbers, identifiers, references - separately to the management of spatial objects.

This Feature / Feature Naming separation applies to Geographical objects, Roads and Administrative Areas as well as Addresses and the first two of those three objects have models similar to this one for their names, <<GN>> & <<ROADS>>.

Some elements of this Feature / Feature Naming pattern, used by this and the two models mentioned above, are captured in the general-purpose _Compound Naming Model_ <<CNM>> which they all inherit from.


==== Feature / Geometry differentiation

(Geo)spatial objects referenced by this model are not geometries but conceptual spatial objects that may have as an expression of their spatial projection one or more geometries. This conceptual object / spatial expression differentiation, which we refer to as a Feature / Geometry split, is based on fundamental spatial modelling in standards such as <<ISO19101-1>> and their expression in the Semantic Web spatial standard <<GEO>>.

This Feature / Geometry split allows individual spatial objects to have multiple Geometries: different resolutions, in different coordinate systems and even sets of Geometries that have different roles or that show variation over time.

While this model doesn't model spatial aspects of the object to which addresses are assigned - see the section above - this Feature / Geometry split and expressions of geometry are modelled for geocodes - see next section.


==== Geocodes

Geocodes are spatial objects - Features - with point geometries that addresses may be associated with so that they can be used by mapping applications to locate the address, or part of an addressable object, on a map or on the earth.

Geocodes may be only indirectly related to an Addressable Object: while they may be calculated from them, for example they could be the centroid of a lot, they may also not be, for example they could be a GPS-marked point indicating a property entrance point that is on or close to the Addressable Object but has been determined independently of its details.

For this reason, Geocodes are related to Addresses only in this model, not Addressable Objects, and any Geocode/Addressable Object relations are out-of-scope here.


=== Address Parts

Addresses are complex things: they are all made of multiple parts with different roles, types ordering and so on. To handle this, this model has a generic notion of a part which may be a simple thing, e.g. a postcode or a street number, but it may also be a complex thing, e.g. a road name that includes a "given" name for the road as well as some type indication.

This model inherits from the Compound Naming Model <<CNM>> which allows for Compound Names, such as Addresses, to link to parts which are also Compound Names which then link to other Compound Names. In this way, Addresses may be "built up" from compound names for a series of parts, such as road names, locality names and so on.

==== Road & Geographical Names

This model can be used to model all the parts of a street names - the 'given' part e.g. "Smith", a type indicator such as "Street" and perhaps a suffix, such as "South" - or it can be used to just indicate that a particular street or road is a part of an address and the name for that road is to be found in an independent road name object.

This second form - delegation of name - is allowed to facilitate point-of-truth road names datasets which both provide names for roads in isolation and are also used by address datasets.

Similarly, names for geographical objects, such as mountains, lakes, certain kinds of locality etc. may also be held independently of addressing data and just referred to as a complex object part of an address.

A model of roads - both naming and some physical presentation of them - has been created in parallel to this model, as has a model of Geographical Names which is a replacement for the various Placenames models found in ANZ, such as the https://linked.data.gov.au/def/placenames[FSDF Placenames Ontology]. these models can be used independently as well as within this model. Their persistent web addresses are:

* https://linked.data.gov.au/def/roads - Roads Model
* https://linked.data.gov.au/def/gn - Geographical Names Model


== Address part typing

There are various given name parts of addresses which have previously been shoved into inappropriate data fields legacy address models and systems. For example, some models have contained _building_ but not _property_ names, so both types have been combined into the field for the former.

In this model, all address parts are just parts with a specialised type indicated with a reference to a concept within a vocabulary such as the Address Parts vocabulary (see <<Supporting Vocabularies>>). Implementations _MUST_ allow for this type of "soft typing" (where a data object's type is selectable from an external list) so that no field limitations such as the above occur.

Implementers can limit the part type vocabulary of course and will have to handel all the types they allow in the vocabulary, but implementers should not "make do" with inappropriate field (part type) reuse.


==== Address part templating

TODO

// templating


==== Water Addressing

TODO

==== Related Addresses

TODO

// Property Addressing
// Aliases
// Parent-child


==== Lifecycles

TODO


==== Profile Views

Addresses have multiple roles: they indicate places with names (or Features with Labels), they are things to be managed by data holders, and they have statuses, lifecycles and so on. Sometimes we are only interested in one of these aspects of an Address or one _profile_ and not the total Address information held. We may also be interested only in a reduced set of properties of an Address even when others within that role are present, e.g. the current status, not all the statues an Address has ever had. Finally, different implementers of this model may want to implement different jurisdictional profiles of the entire model that, for example, mandate records for that jurisdiction's system's use of Addresses that would be meaningless outside that jurisdiction.

All of these sorts of _profiles_ of Addresses are handled in a similar way in this model: they are declared Profiles of the model that may implement additional rules and/or requirements on data, however they must always conform to the main Address Model itself.

Profile modelling is given in <<PROF>> and requesting profiles from data conforming to a model is given in <<CONNEGP>>.


=== Model resources

This document is this model's "Specification" which is its authoritative, human-readable, definition document. This model also contains other resources with other roles:

[width="75%", cols="2,1,4"]
|===
| Resource | Role | Notes

| https://spatial-information-qld.github.io/address-model/model.ttl[Ontology] | _Schema_ | The technical, machine-readable, version of this model
| <<Supporting Vocabularies>> | _Vocabulary_ | The codelist vocabularies developed for this model and links to others  defined elsewhere but used by this model
| <<AnnexA>> | _Guidance_ | The Requirements addressed by this model
| <<AnnexB>> & https://github.com/Spatial-Information-QLD/address-model/blob/main/validator.ttl[Validator] | _Validation_ | The machine-readable validator file used to validate data claiming conformance to this model
| <<AnnexC>>
&
https://github.com/Spatial-Information-QLD/address-model/tree/main/extended-examples[Extended example data files] | _Example_ | Examples of data conforming, and some not conforming, to this model
| <<AnnexD>> | _Example_ | Demonstration implementations of this model in various database forms
|===
