= Contributing

Queensland Spatial Information (QSI) welcomes contributions to this open source standard. Anybody may contribute and QSI will apply serious consideration to all edits.

== How to lodge a contribution

Please contribute however you can. In best case, you should lodge technical Pull Requests with changes to the content of this repository.

You could also lodge any Issues, without fixes proposed, at the Issue Tracker:

* https://github.com/spatial-information-QLD/address-model/issues

If you are not able to lodge a Pull Request or an Issue, please describe your suggested changes, with reference to specific model documentation or other elements via emails to this model's contacts, see the [repository's contacts section](https://github.com/spatial-information-QLD/address-model#contacts).

== How to technically edit the model documentation

This model document is created using the ASCIIDoctor documentation system, see https://asciidoctor.org. Please just search for help regarding ASCIIDoc setup and use, there is plenty of help online.

When updated and merged into this repository, the source files for this model's documentation are auto-built into the rendered document online at https://linked.data.gov.au, so you don't have to actually make the file document, just alter the source files.

The ASCIIDoc source files are all reached from the index file 00-master.adoc.

