= ICSM Address Model

This repository contains the source files for the https://www.icsm.gov.au[ICSM] Address Model for Australian & New Zealand.

To view the model, go to its permanent online location:

* *https://linked.data.gov.au/def/addr*

== Status

This model was developed by Spatial Information Queensland in response to the ICSM's Addressing 2035 Strategy and was voted in as the ICSM Address Model for all jurisdictions and data exchange by the ICSM Addressing Working Group in June, 2024.

== Model technical details

=== Documentation

The model documentation, online at the above location, is created using https://asciidoc.org/[ASCIIDOC], the documentation system also used by many ISO and OGC standards.

The source files used are in this repository with the master document being `00-master.adoc`.

This repository is directly accessible at:

* https://github.com/icsm-au/addr-model

To contribute to this model, see the link:https://github.com/icsm-au/addr-model/blob/main/Contributing.adoc[notes on contributing] which describes both technical aspects of editing and community processes.

=== Machine-readable schema

The schema of this model in machine-readable form is presented as an https://www.w3.org/RDF/[RDF] / https://www.w3.org/OWL/[OWL] model in the file `model.ttl` in this repository which is online at https://linked.data.gov.au/def/addr.ttl and at https://linked.data.gov.au/def/addr via https://developer.mozilla.org/en-US/docs/Web/HTTP/Content_negotiation[Content Negotiation] for Turtle data.

Additionally, there is a https://www.w3.org/TR/shacl/[SHACL] validator for this model available online at https://linked.data.gov.au/def/addr/validator.

== Rights and License

The content of this repository and the Address Model overall have the following copyright notices:

&copy; The State of Queensland (Department of Resources), 2020 - 2023
&copy; Commonwealth of Australia on behalf of ICSM, 2024

All content here is available for reuse under the https://creativecommons.org/licenses/by/4.0/[Creative Commons 4.0 license], see the LICENSE file for the deed.

Note that much of the content in this model is reused from other models that have their own copyright and ruse information but all implement permissive open source Apache or BSD or W3C licenses that are similar to Creative Commons licenses.

== Contacts

For more information about this model, contact:

*Chairperson of the Addressing Working Group* +
via ICSM at ICSM@ga.gov.au

or

*Spatial Information* +
Department of Resources +  
Queensland Government +
CadastralAdminDataHelp@resources.qld.gov.au

For technical model implementation questions, contact:

*Nicholas Car* +
https://kurrawong.ai[KurrawongAI] +
nick@kurrawong.ai +
_Contractor to Spatial Information Qld._
