= Spatial Information Queensland - Address Model

A Semantic Web data model of address information that caters specifically for Australian & New Zealand's address modelling needs.

This model's specification document is auto-built from the source file `00-master.adoc` and is viewable online at the following persistent web address:

* *https://linked.data.gov.au/def/addr*

The repository is at:

* https://github.com/Spatial-Information-QLD/address-model

To contribute to this model, see the link:https://github.com/Spatial-Information-QLD/address-model/blob/main/Contributing.adoc[notes on contributing] which describe both technical aspects of editing and community processes.

== Rights and License

Content generated by Spatial Information Queensland is copyright as follows:

&copy; The State of Queensland (Department of Resources), 2023

This information is available for reuse under the https://creativecommons.org/licenses/by/4.0/[Creative Commons 4.0 license], see the LICENSE file for the deed.

Much of the vocabulary content here is copied from elsewhere and, where this has occurred, the vocabulary source is noted so that the source information licensing and rights may be discovered.

== Contacts

For more information about these vocabularies, contact:

*Spatial Information* +
GeoResources Division +
Department of Resources +  
Queensland Government +
CadastralAdminDataHelp@resources.qld.gov.au 

For further information, please visit:

https://www.resources.qld.gov.au/data-mapping +  
https://qldspatial.information.qld.gov.au/

For technical model implementation questions, contact:

*Nicholas Car* +
nick@kurrawong.ai +
_Contractor to Spatial Information Qld._
